spring:
  session:
    store-type: redis
  cache:
    type: redis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aw2022
    username: root
    password: 191820091
#  redis:
#    cluster:
#      nodes:
#        - 192.168.198.128:6379
#        - 192.168.198.128:6380
#        - 192.168.198.128:6381